### ISSUE TITLE
Precision of numbers?

### ISSUE THREAD

**Issue by PaulBernier** [Factom-Asset-Tokens/fat-js#1]
Quickly looking I didn't see a dependency on http://mikemcl.github.io/bignumber.js/ (or similar libraries). I think it is necessary to work with such a library when manipulating big numbers or numbers with decimals up to 10^-10 (as per your spec). You can see that web3.js uses it: https://github.com/ethereum/wiki/wiki/JavaScript-API#a-note-on-big-numbers-in-web3js

**Comment by drkatz** [comment]
Closed in https://github.com/Factom-Asset-Tokens/fat-js/commit/e474981e9a342d6e9768fa1d03a86462da45ad29
