### ISSUE TITLE
Add support for pending balances and pending transactions

### ISSUE THREAD

**Issue by PaulBernier** [Factom-Asset-Tokens/fat-js#10]
fatd 1.0 is now supposed to support both pending balances and transactions and I believe this does require some changes in fat-js to be supported. If not, a short explanation of how to use it would be welcomed and the issue can be closed. Thanks!

**Comment by drkatz** [comment]
This was merged with development in c3703d2b734bc700e2cf3b127d0f29bbce317b71 on Sept 10.

Thanks!

**Comment by drkatz** [comment]
Merged to master in 96228ea50a100a240c8672eebf40111f1ce49e97
