### ISSUE TITLE
Self sending transactions are rejected

### ISSUE THREAD

**Issue by PaulBernier** [Factom-Asset-Tokens/fat-js#11]
fatd 1.0 authorize an address to be both in input and output but fat-js reject those transactions with errors `Output address already occurs in inputs` or `Input address already occurs in inputs`

**Comment by drkatz** [comment]
Please see branch https://github.com/Factom-Asset-Tokens/fat-js/tree/zero-input-zero-output-send-to-self.

I will leave this open for convenience and tracking until the branch is merged
