### ISSUE TITLE
Issuance metadata not populated with fatd response to get-issuance

### ISSUE THREAD

**Issue by PaulBernier** [Factom-Asset-Tokens/fat-js#4]
Both for FAT0 and FAT1.

https://github.com/Factom-Asset-Tokens/fat-js/blob/master/0/Issuance.js#L61
https://github.com/Factom-Asset-Tokens/fat-js/blob/master/1/Issuance.js#L57

**Comment by drkatz** [comment]
Thank you. To add the integration test for this fix I'll need to issue some new tokens and reprogram the current smoke tests for FAT-0/1 issuances for those. Expect this soon!
